### ISSUE TITLE
Econnreset between node-red and Zway server

### ISSUE THREAD

**Issue by Vinisz** [bkorda/node-red-contrib-zway#2]
** Describe issue **
Hi, Making good use of your nodes for node-red to zway, however..
Now I suddenly get "ECONNRESET" errors in node-red from time to time and it seems like zway server cannot keep up. 
Do you know if there is some kind of limit I'm hitting maybe ? I have around 137 z-wave nodes and quite some flows in node-red.

Thanks for your help.

Greetings,

Vincent.

**Comment by bkorda** [comment]
Hi, thank you for your report. I didn't meet this error and community who use it too. I'm not sure if there are some limits. Maybe you can share more information about the error. Screenshots, versions etc

**Comment by Vinisz** [comment]
I think it was caused by a loop in the flow, consider it no issue anymore.
