### ISSUE TITLE
NodOn Soft remote 

### ISSUE THREAD

**Issue by arachnida** [bkorda/node-red-contrib-zway#6]
I'm using a Nodon Soft remote. The 4 buttons work and the messages are transferred to the Node-Red node, but only the first press of a button. So if I click button 1 and after a while I click button 1 again the second click is not visible in my debug window. If I however click another button the node sends the corresponding message. If I look at my Zway screen I can see the time of the last click being updated in the elements window, so the Zwave signal does arrive at the Zway controller, but the node doesn't do anything. Also if I double click or hold the previous button the node reacts to the first instance of this event, but not a second time.

I'm using the State output of the node, not the homekit.

** Hardware / Software **
  - raspberry 4   
  - version of zway firmware version: [v3.0.4] 
  - zway UI version: [1.10.2]
  - version of node-red-contrib-zway: [0.2.2]

**Comment by bkorda** [comment]
Thank you. I have no any remotes. I can check only errors in my code and maybe ask someone to debug.

**Comment by arachnida** [comment]
Hi, this seems to be a bug in the Z-way software, a duplicate event is not logged but filtered out. For remote controls however this behaviour is not wanted. This issue will be solved in a next release of the Z-way software I'm promised by Serguei.
So no need to search for this bug, it will be solved after the next release of Z-Way.
