### ISSUE TITLE
Unable to use complex passwords

### ISSUE THREAD

**Issue by isMnemonic** [bkorda/node-red-contrib-zway#8]
Using complex passwords does not work with this node package.
Example of password(fully functional in Z-way admin page): tV5"uP5(wI8$qB3#zE4"eZ3+fS6"sQ7%

** Hardware / Software **
  - raspberry 3 model b rev 1.2
  - version of zway firmware version: 3.1.1
  - zway UI version: 1.11
  - version of node-red-contrib-zway: 0.2.3

**Comment by bkorda** [comment]
Thank you for feedback. Unfortunately I can't fix it now because my hardware is broken. Maybe someone can make a pull request?

**Comment by PoltoS** [comment]
This fix (not tested as we don't have node-red) uses Z-Way token instead of login/password: https://github.com/bkorda/node-red-contrib-zway/pull/11

May be it will make this issue irrelevant

**Comment by bkorda** [comment]
Will update to support Z-Way Authentication token.
