### ISSUE TITLE
old embedded jQuery module "multiple-select" v1.4.1 breaks monaco-editor in node-red 2.0.0

### ISSUE THREAD

**Issue by Steve-Mcl** [bkorda/node-red-contrib-zway#9]
** Describe issue **
Hi, much like the [issue I raised on node-red-contrib-zigbee2mqtt](https://github.com/andreypopov/node-red-contrib-zigbee2mqtt/issues/41), this repo also has an old version of "multiple-select" embedded in the `static/` folder that breaks the new monaco editor (See [here](https://discourse.nodered.org/t/node-red-2-0-0-beta-1-released/46990/84?u=steve-mcl))

The issue is (i believe) specific to multiple-select V1.4.2 and below - see this issue: wenzhixin/multiple-select#483

Could you please update to V1.5.2 as it does not cause the editor to break.

** Screens / Logs **
![image](https://user-images.githubusercontent.com/44235289/121816618-94397c00-cc74-11eb-8c0c-29ec35b50697.png)

**Comment by bkorda** [comment]
Sorry, I have no soft and hardware to test, need to find a new device. Could you do a pull request?

**Comment by Steve-Mcl** [comment]
Hi, sorry, I don't have hardware either. All I can say is most of the other nodes which I flagged have just updated the local copy of the jQuery file



E.g. look at 
node-red-contrib-zigbee2mqtt and node-red-contrib-deconz change log.

**Comment by bkorda** [comment]
Hey, sorry for such a big silence. Will update it as soon as possible

**Comment by bkorda** [comment]
Fixed in node-red-contrib-zway@1.0.0
